# clip board - cliphist
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data

# Extra user
exec-once = uwsm app -- vesktop
#exec-once = flatpak run com.valvesoftware.Steam &
#exec-once = youtube-music &
#exec-once = uwsm app --  noisetorch -i
exec-once = uwsm app -- trayscale --hide-window
exec-once = uwsm app -- syncthingtray-qt6

