$mon1Desc=desc:ASUSTek COMPUTER INC VG32AQA1A S9LMQS118414
$mon1Id=DP-3

$mon2Desc=desc:Philips Consumer Electronics Company PHL 241V8LB UK02327029074
$mon2Id=DP-2

$mon3Desc=desc:
$mon3Id=HDMI-A-1

#monitor= name, resolution, position, scale,
monitor=DP-3, preferred, auto, auto, vrr, 1
monitor=DP-2, preferred, auto-left, auto 
#monitor=, # TODO: primary monitor at school


workspace=1, monitor:DP-3, default:true
workspace=2, monitor:DP-3
workspace=3, monitor:DP-3

workspace=4, monitor:DP-2, default:true
workspace=5, monitor:DP-2
workspace=6, monitor:DP-2

#workspace=7, monitor:$mon3Id, default:true
#workspace=8, monitor:$mon3Id
#workspace=9, monitor:$mon3Id

workspace = special:scratchpad:
