"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 2000

format = """
$cmd_duration\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$bun\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
\\[$username@$hostname $os $container $directory\\]$character
"""

[mise]
disabled = false
format = "\\[[$health ]($style)\\]"
style = "bold purple"
detect_files = [
    "mise.toml",
    "mise.local.toml",
    ".mise.toml",
    ".mise.local.toml",
]
detect_folders = [".mise", "mise-tasks"]
healthy_symbol = ""
unhealthy_symbol = ""


[character]
error_symbol = "[\\$](bold red)"
success_symbol = "[\\$](bold green)"

[aws]
disabled = true

[bun]
symbol = ""
format = '\[[$symbol ($version)]($style)\]'

[c]
disabled = true

[cpp]
disabled = true

[cmake]
disabled = true


[cmd_duration]
format = '\[󱎫 $duration\]'

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
symbol = ""
format = '\[[$symbol ($version)]($style)\]'

[docker_context]
format = '\[[$symbol $context]($style)\]'

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ""
format = '\[[$symbol $branch]($style)\]'

[git_status]
format = '([\[$all_status $ahead_behind\]]($style))'

[golang]
disabled = true

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[java]
symbol = ""
format = '\[[$symbol ($version)]($style)\]'

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
symbol = ""
format = '\[[$symbol ($version)]($style)\]'

[memory_usage]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
symbol = "󰎙"
format = '\[[$symbol ($version)]($style)\]'

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = false
format = '[$symbol]($style)'

[os.symbols]
Alpine = " "
Arch = "󰣇 "
Debian = " "
Gentoo = " "
Linux = " "
Mint = "󰣭 "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = "󰖳 "


[package]
symbol = ""
format = '\[[$symbol $version]($style)\]'

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pixi]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
symbol = ""
format = '\[[${symbol} ${version} (\($virtualenv\))]($style)\]'

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
symbol = "󱘗"
format = '\[[$symbol ($version)]($style)\]'

[scala]
disabled = true

[spack]
disabled = true

[sudo]
disabled = true
format = '\[[as $symbol]($style)\]'

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[username]
show_always = true
format = '[$user]($style)'

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true

[solidity]
disabled = true

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'

[directory]
truncation_length = 1
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = false

[netns]
disabled = true
